import type { Employee, AttendanceRecord, TimeOffRequest } from '../types/hrms';
import { generateLoginId } from '../utils/salaryCalculator';

export const initialEmployees: Employee[] = [
  {
    id: 'emp-1',
    loginId: generateLoginId('Odoo India', 'Speedy Crab', 2022, 1), // OISPCR20220001
    name: 'Speedy Crab',
    email: 'speedy.crab@odoo.com',
    role: 'admin',
    company: 'Odoo India',
    department: 'Human Resources',
    jobTitle: 'HR Director / Admin',
    manager: 'CEO Office',
    location: 'Gandhinagar, Gujarat',
    mobile: '+91 98765 43210',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    presenceStatus: 'present',
    dob: '1990-05-15',
    gender: 'Female',
    maritalStatus: 'Married',
    nationality: 'Indian',
    address: 'Block A, Infocity, Gandhinagar, Gujarat 382007',
    personalEmail: 'speedy.crab.personal@gmail.com',
    phone: '+91 98765 43210',
    dateOfJoining: '2022-01-10',
    accountNumber: '918237465012',
    bankName: 'HDFC Bank',
    ifscCode: 'HDFC0001234',
    panNo: 'ABCDE1234F',
    uanNo: '100987654321',
    employeeCode: 'EMP001',
    monthlyWage: 75000,
    workingDaysPerWeek: 5,
    breakTimeHours: 1,
    about: 'Experienced HR executive managing operations, employee welfare, and enterprise payroll setup at Dayflow.',
    whatILove: 'Fostering inclusive workplace culture and optimizing automated HR workflows.',
    interests: 'Tech Blogging, Chess, Classical Music',
    skills: [
      { id: 's1', name: 'Strategic HR Management', level: 'Expert' },
      { id: 's2', name: 'Payroll & Compliance', level: 'Expert' },
      { id: 's3', name: 'Talent Acquisition', level: 'Advanced' },
    ],
    certifications: [
      { id: 'c1', name: 'SHRM Senior Certified Professional (SHRM-SCP)', issuer: 'SHRM', year: '2021' },
      { id: 'c2', name: 'Certified Compensation Professional (CCP)', issuer: 'WorldatWork', year: '2023' },
    ],
    paidTimeOffAvailable: 24,
    sickTimeOffAvailable: 7,
  },
  {
    id: 'emp-2',
    loginId: generateLoginId('Odoo India', 'Splendid Chamois', 2022, 2), // OISPCH20220002
    name: 'Splendid Chamois',
    email: 'splendid.chamois@odoo.com',
    role: 'employee',
    company: 'Odoo India',
    department: 'Engineering',
    jobTitle: 'Senior Frontend Developer',
    manager: 'Speedy Crab',
    location: 'Gandhinagar, Gujarat',
    mobile: '+91 98765 43211',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    presenceStatus: 'present',
    dob: '1994-08-22',
    gender: 'Male',
    maritalStatus: 'Single',
    nationality: 'Indian',
    address: 'Sector 11, Gandhinagar, Gujarat 382011',
    personalEmail: 'splendid.chamois@gmail.com',
    phone: '+91 98765 43211',
    dateOfJoining: '2022-03-15',
    accountNumber: '918237465013',
    bankName: 'ICICI Bank',
    ifscCode: 'ICIC0000456',
    panNo: 'FGHIJ5678K',
    uanNo: '100987654322',
    employeeCode: 'EMP002',
    monthlyWage: 50000,
    workingDaysPerWeek: 5,
    breakTimeHours: 1,
    about: 'Passionate UI/UX specialist crafting accessible React 19 web interfaces.',
    whatILove: 'Building high performance web applications with pixel perfect design.',
    interests: 'UI Prototyping, Photography, Mountain Biking',
    skills: [
      { id: 's1', name: 'React & TypeScript', level: 'Expert' },
      { id: 's2', name: 'Tailwind CSS', level: 'Expert' },
      { id: 's3', name: 'Framer Motion', level: 'Advanced' },
    ],
    certifications: [
      { id: 'c1', name: 'Meta Front-End Developer Specialization', issuer: 'Coursera', year: '2022' },
    ],
    paidTimeOffAvailable: 24,
    sickTimeOffAvailable: 7,
  },
  {
    id: 'emp-3',
    loginId: generateLoginId('Odoo India', 'Altruistic Tiger', 2023, 3), // OIALTI20230003
    name: 'Altruistic Tiger',
    email: 'altruistic.tiger@odoo.com',
    role: 'employee',
    company: 'Odoo India',
    department: 'Product',
    jobTitle: 'Product Manager',
    manager: 'Speedy Crab',
    location: 'Ahmedabad, Gujarat',
    mobile: '+91 98765 43212',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    presenceStatus: 'absent',
    dob: '1992-11-04',
    gender: 'Male',
    maritalStatus: 'Married',
    nationality: 'Indian',
    address: 'Satellite Road, Ahmedabad, Gujarat 380015',
    personalEmail: 'altruistic.tiger@gmail.com',
    phone: '+91 98765 43212',
    dateOfJoining: '2023-02-01',
    accountNumber: '918237465014',
    bankName: 'State Bank of India',
    ifscCode: 'SBIN0001122',
    panNo: 'KLMNO9012P',
    uanNo: '100987654323',
    employeeCode: 'EMP003',
    monthlyWage: 60000,
    workingDaysPerWeek: 5,
    breakTimeHours: 1,
    about: 'Product strategist focused on enterprise workflow automation.',
    whatILove: 'Solving complex operational roadblocks for client teams.',
    interests: 'Product Strategy, Podcasts, Travel',
    skills: [
      { id: 's1', name: 'Agile & Scrum', level: 'Expert' },
      { id: 's2', name: 'Product Analytics', level: 'Advanced' },
    ],
    certifications: [
      { id: 'c1', name: 'Certified Scrum Product Owner (CSPO)', issuer: 'Scrum Alliance', year: '2023' },
    ],
    paidTimeOffAvailable: 20,
    sickTimeOffAvailable: 6,
  },
  {
    id: 'emp-4',
    loginId: generateLoginId('Odoo India', 'Fearless Hummingbird', 2023, 4), // OIFEHU20230004
    name: 'Fearless Hummingbird',
    email: 'fearless.hummingbird@odoo.com',
    role: 'employee',
    company: 'Odoo India',
    department: 'Quality Assurance',
    jobTitle: 'QA Lead',
    manager: 'Speedy Crab',
    location: 'Gandhinagar, Gujarat',
    mobile: '+91 98765 43213',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    presenceStatus: 'leave',
    dob: '1995-03-30',
    gender: 'Female',
    maritalStatus: 'Single',
    nationality: 'Indian',
    address: 'Kudasan, Gandhinagar, Gujarat 382421',
    personalEmail: 'fearless.hummingbird@gmail.com',
    phone: '+91 98765 43213',
    dateOfJoining: '2023-06-12',
    accountNumber: '918237465015',
    bankName: 'Axis Bank',
    ifscCode: 'UTIB0000888',
    panNo: 'PQRST3456U',
    uanNo: '100987654324',
    employeeCode: 'EMP004',
    monthlyWage: 48000,
    workingDaysPerWeek: 5,
    breakTimeHours: 1,
    about: 'Dedicated QA engineer ensuring seamless software releases.',
    whatILove: 'Automated testing and breaking edge-case scenarios.',
    interests: 'Automated Testing, Gaming, Reading',
    skills: [
      { id: 's1', name: 'Cypress & Playwright', level: 'Expert' },
      { id: 's2', name: 'Jest / Vitest', level: 'Advanced' },
    ],
    certifications: [
      { id: 'c1', name: 'ISTQB Certified Tester', issuer: 'ISTQB', year: '2022' },
    ],
    paidTimeOffAvailable: 22,
    sickTimeOffAvailable: 5,
  },
  {
    id: 'emp-5',
    loginId: generateLoginId('Odoo India', 'Stunning Falcon', 2024, 5), // OISTFA20240005
    name: 'Stunning Falcon',
    email: 'stunning.falcon@odoo.com',
    role: 'employee',
    company: 'Odoo India',
    department: 'Design',
    jobTitle: 'UI/UX Designer',
    manager: 'Speedy Crab',
    location: 'Gandhinagar, Gujarat',
    mobile: '+91 98765 43214',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    presenceStatus: 'present',
    dob: '1996-09-18',
    gender: 'Female',
    maritalStatus: 'Single',
    nationality: 'Indian',
    address: 'Raysan, Gandhinagar, Gujarat 382426',
    personalEmail: 'stunning.falcon@gmail.com',
    phone: '+91 98765 43214',
    dateOfJoining: '2024-01-05',
    accountNumber: '918237465016',
    bankName: 'HDFC Bank',
    ifscCode: 'HDFC0001234',
    panNo: 'VWXYZ7890A',
    uanNo: '100987654325',
    employeeCode: 'EMP005',
    monthlyWage: 45000,
    workingDaysPerWeek: 5,
    breakTimeHours: 1,
    about: 'Creative visual designer translating complex user flows into elegant interfaces.',
    whatILove: 'Color theory, design tokens, and sleek component libraries.',
    interests: 'Figma Prototyping, Digital Art, Typography',
    skills: [
      { id: 's1', name: 'Figma & Design Systems', level: 'Expert' },
      { id: 's2', name: 'User Research', level: 'Advanced' },
    ],
    certifications: [
      { id: 'c1', name: 'Google UX Design Professional Certificate', issuer: 'Google', year: '2023' },
    ],
    paidTimeOffAvailable: 24,
    sickTimeOffAvailable: 7,
  },
];

export const initialAttendanceRecords: AttendanceRecord[] = [
  {
    id: 'att-101',
    employeeId: 'emp-1',
    employeeName: 'Speedy Crab',
    date: '2026-08-22',
    checkIn: '09:00 AM',
    checkOut: '06:00 PM',
    workHours: '09:00',
    extraHours: '01:00',
    status: 'present',
  },
  {
    id: 'att-102',
    employeeId: 'emp-2',
    employeeName: 'Splendid Chamois',
    date: '2026-08-22',
    checkIn: '09:15 AM',
    checkOut: '06:15 PM',
    workHours: '09:00',
    extraHours: '01:00',
    status: 'present',
  },
  {
    id: 'att-103',
    employeeId: 'emp-3',
    employeeName: 'Altruistic Tiger',
    date: '2026-08-22',
    checkIn: '',
    checkOut: '',
    workHours: '00:00',
    extraHours: '00:00',
    status: 'absent',
  },
  {
    id: 'att-104',
    employeeId: 'emp-4',
    employeeName: 'Fearless Hummingbird',
    date: '2026-08-22',
    checkIn: '',
    checkOut: '',
    workHours: '00:00',
    extraHours: '00:00',
    status: 'leave',
  },
  {
    id: 'att-105',
    employeeId: 'emp-5',
    employeeName: 'Stunning Falcon',
    date: '2026-08-22',
    checkIn: '09:30 AM',
    checkOut: '06:30 PM',
    workHours: '09:00',
    extraHours: '01:00',
    status: 'present',
  },
  // Previous dates for personal daywise attendance display
  {
    id: 'att-201',
    employeeId: 'emp-2',
    employeeName: 'Splendid Chamois',
    date: '2026-08-21',
    checkIn: '09:00 AM',
    checkOut: '06:00 PM',
    workHours: '09:00',
    extraHours: '01:00',
    status: 'present',
  },
  {
    id: 'att-202',
    employeeId: 'emp-2',
    employeeName: 'Splendid Chamois',
    date: '2026-08-20',
    checkIn: '09:00 AM',
    checkOut: '06:00 PM',
    workHours: '09:00',
    extraHours: '01:00',
    status: 'present',
  },
];

export const initialTimeOffRequests: TimeOffRequest[] = [
  {
    id: 'to-1',
    employeeId: 'emp-4',
    employeeName: 'Fearless Hummingbird',
    type: 'Sick Leave',
    startDate: '2026-08-22',
    endDate: '2026-08-24',
    durationDays: 3,
    status: 'Pending',
    attachmentName: 'medical_certificate.pdf',
    createdAt: '2026-08-21',
  },
  {
    id: 'to-2',
    employeeId: 'emp-3',
    employeeName: 'Altruistic Tiger',
    type: 'Paid Time Off',
    startDate: '2026-08-28',
    endDate: '2026-08-30',
    durationDays: 3,
    status: 'Approved',
    createdAt: '2026-08-18',
  },
  {
    id: 'to-3',
    employeeId: 'emp-2',
    employeeName: 'Splendid Chamois',
    type: 'Paid Time Off',
    startDate: '2026-09-01',
    endDate: '2026-09-05',
    durationDays: 5,
    status: 'Pending',
    createdAt: '2026-08-20',
  },
];
