# Generated by Django 5.2.17 on 2026-08-22 05:16

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Leave Type Name')),
                ('code', models.CharField(help_text='Short code (e.g. CL, SL, PL, UL)', max_length=20, unique=True, verbose_name='Code')),
                ('max_days_per_year', models.DecimalField(decimal_places=1, default=Decimal('12.0'), max_digits=4, verbose_name='Max Days Allowed Per Year')),
                ('is_paid', models.BooleanField(default=True, verbose_name='Is Paid Leave')),
                ('requires_attachment', models.BooleanField(default=False, verbose_name='Requires Medical / Supporting Attachment')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Leave Type',
                'verbose_name_plural': 'Leave Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('total_days', models.DecimalField(decimal_places=1, default=Decimal('1.0'), max_digits=4, verbose_name='Total Days Requested')),
                ('reason', models.TextField(verbose_name='Reason for Leave')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='leave_attachments/', verbose_name='Supporting Document / Medical Certificate')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20, verbose_name='Approval Status')),
                ('applied_on', models.DateTimeField(auto_now_add=True, verbose_name='Applied On')),
                ('rejection_reason', models.TextField(blank=True, null=True, verbose_name='Remarks / Reason for Rejection')),
                ('action_taken_at', models.DateTimeField(blank=True, null=True, verbose_name='Action Taken At')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_leaves', to=settings.AUTH_USER_MODEL, verbose_name='Reviewed By')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='employees.employee', verbose_name='Employee')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leave_requests', to='leave.leavetype', verbose_name='Leave Type')),
            ],
            options={
                'verbose_name': 'Leave Request',
                'verbose_name_plural': 'Leave Requests',
                'ordering': ['-applied_on'],
                'indexes': [models.Index(fields=['status', 'start_date'], name='leave_leave_status_787f14_idx'), models.Index(fields=['employee', 'status'], name='leave_leave_employe_521ced_idx')],
            },
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='Year')),
                ('total_allocated', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=4, verbose_name='Total Allocated Days')),
                ('used_days', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=4, verbose_name='Consumed Days')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to='employees.employee', verbose_name='Employee')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='leave.leavetype', verbose_name='Leave Type')),
            ],
            options={
                'verbose_name': 'Leave Balance',
                'verbose_name_plural': 'Leave Balances',
                'ordering': ['-year', 'employee'],
                'unique_together': {('employee', 'leave_type', 'year')},
            },
        ),
    ]
