# Generated by Django 5.2.17 on 2026-08-22 05:16

import datetime
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, default=datetime.date.today, verbose_name='Attendance Date')),
                ('check_in', models.TimeField(blank=True, null=True, verbose_name='Check-In Time')),
                ('check_out', models.TimeField(blank=True, null=True, verbose_name='Check-Out Time')),
                ('work_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Computed duration between check-in and check-out in hours', max_digits=5, verbose_name='Total Work Hours')),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('HALF_DAY', 'Half Day'), ('ON_LEAVE', 'On Leave'), ('LATE', 'Late Arrival'), ('WFH', 'Work From Home')], db_index=True, default='PRESENT', max_length=20, verbose_name='Attendance Status')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Remarks / Reason for Late or WFH')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='employees.employee', verbose_name='Employee')),
            ],
            options={
                'verbose_name': 'Attendance Record',
                'verbose_name_plural': 'Attendance Records',
                'ordering': ['-date', 'employee'],
                'indexes': [models.Index(fields=['date', 'status'], name='attendance__date_3889e6_idx'), models.Index(fields=['employee', 'date'], name='attendance__employe_08d913_idx')],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
