# Generated by Django 5.2.17 on 2026-08-22 05:16

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_wage', models.DecimalField(decimal_places=2, help_text='Total cost to company per month', max_digits=12, verbose_name='Monthly Wage (CTC)')),
                ('yearly_wage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='12 * monthly_wage', max_digits=12, verbose_name='Yearly Wage (CTC)')),
                ('basic_salary', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Calculated at 50% of monthly wage', max_digits=12, verbose_name='Basic Salary')),
                ('hra', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Calculated at 50% of Basic Salary', max_digits=12, verbose_name='House Rent Allowance (HRA)')),
                ('standard_allowance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Standard Allowance')),
                ('performance_bonus', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Performance Bonus')),
                ('leave_travel_allowance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Leave Travel Allowance (LTA)')),
                ('fixed_allowance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Remaining monthly wage allocation', max_digits=12, verbose_name='Fixed / Special Allowance')),
                ('provident_fund', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Calculated at 12% of Basic Salary', max_digits=12, verbose_name='Provident Fund (PF)')),
                ('professional_tax', models.DecimalField(decimal_places=2, default=Decimal('200.00'), max_digits=12, verbose_name='Professional Tax (PT)')),
                ('other_deductions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Other Deductions')),
                ('gross_salary', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Gross Monthly Salary')),
                ('total_deductions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total Deductions')),
                ('net_salary', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Gross salary minus total deductions', max_digits=12, verbose_name='Net Salary (In-Hand)')),
                ('effective_from', models.DateField(verbose_name='Effective Date')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active Salary Structure')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salary_structure', to='employees.employee', verbose_name='Employee')),
            ],
            options={
                'verbose_name': 'Salary Structure',
                'verbose_name_plural': 'Salary Structures',
                'ordering': ['-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField(choices=[(1, '01'), (2, '02'), (3, '03'), (4, '04'), (5, '05'), (6, '06'), (7, '07'), (8, '08'), (9, '09'), (10, '10'), (11, '11'), (12, '12')], verbose_name='Month')),
                ('year', models.PositiveIntegerField(verbose_name='Year')),
                ('basic_salary', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('hra', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('allowances', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('bonus', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('gross_salary', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('provident_fund', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('professional_tax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('other_deductions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('net_pay', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('payment_status', models.CharField(choices=[('UNPAID', 'Unpaid'), ('GENERATED', 'Generated'), ('PAID', 'Paid')], default='GENERATED', max_length=20, verbose_name='Payment Status')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Payment Date')),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True, verbose_name='Payment Method')),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Transaction / Ref ID')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='employees.employee', verbose_name='Employee')),
            ],
            options={
                'verbose_name': 'Payslip',
                'verbose_name_plural': 'Payslips',
                'ordering': ['-year', '-month', 'employee'],
                'unique_together': {('employee', 'month', 'year')},
            },
        ),
    ]
